config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'homes#top'

  namespace :users do
    resources :posts
    resources :my_pages, only:[:show, :edit, :update]
    get '/my_pages/unsubscribe' => "my_page#unsubscribe"
    patch '/my_pages/withdraw' => "my_page#withdraw"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_one :spot
  has_many :comments
  has_many :post_files, dependent: :destroy
  accepts_attachments_for :post_files, attachment: :image

  paginates_per 10

  validates :fish, presence: true
  validates :fishing, presence: true
  validates :title, presence: true
  validates :text, presence: true

  enum fishing_spot_id: {
    海: 0,
    湖: 1,
    川: 2,
    その他: 3,
  }

  enum spot_type: {
    河川: 0,
    #湖: 1,
    池: 2,
    港: 3,
    堤防: 4,
    海岸: 5,
    磯: 6,
    沖: 7,
    海上釣り掘: 8,
    管理釣り場: 9,
    カセ: 10,
    イカダ: 11,
    #その他: 12,
  }

end

app/models/post_file.rb
class PostFile < ApplicationRecord

  belongs_to :post
  attachment :image


end

app/models/spot.rb
class Spot < ApplicationRecord
  
  belongs_to :post

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments

  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   before_action :configure_permitted_parameters , if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @posts = Post.all
    @posts = Post.page(params[:page]).per(5)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/my_pages_controller.rb
class Users::MyPagesController < ApplicationController

  def show
    @user = User.find(params[:id])
    #@post = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    user.update(user_params)
    #redirect_to users_my_page_path(@user.id)
  end

  def unsubscribe
  end

  def withdraw
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :prefecture,
    :spot, :introduction, :is_active)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController

  def index
    @posts = Post.all
    @posts = Post.page(params[:page]).per(10)
    @post_files = PostFile.all
  end

  def show
    @user = User.find(params[:id])
    @post = Post.find_by(id: params[:id])
  end

  def new
    @post = Post.new
    @post.post_files.build
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to users_post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to users_post_path(@post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    post.destroy
    #redirect_to users_path_path
  end

  private
  def post_params
    params.require(:post).permit(:fishing_spot_id, :spot_type, :fish,
    :fishing, :title, :text, post_files_images: []).merge(user_id:current_user.id)
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users/my_pages_helper.rb
module Users::MyPagesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/views/homes/top.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 fw-normal">釣りのすすめ</h1>
    <p class="lead fw-normal">画像などを使用し釣り場や釣果を釣り場掲示板で報告し合い楽しむことや釣り掲示板の投稿を見ることで近くの釣り場を見つけることを目的としてます。</p>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <h4>投稿一覧</h4>
    </div>
  </div>
</div>

<!--未完成↓-->
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        <div class="card shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <h4 class="card-title">タイトル</h4>
              <p class="card-text">コメントを入れます</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">詳細</button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <h4 class="card-title">タイトル</h4>
              <p class="card-text">コメントを入れます</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">詳細</button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <h4 class="card-title">タイトル</h4>
              <p class="card-text">コメントを入れます</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">詳細</button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsuribanosusume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-info fixed-top">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDropdown" aria-controls="navbarTogglerDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">釣りのすすめ</a>
        <% if user_signed_in? %>
          <a>ようこそ、<%= current_user.name %>さん!!</a>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarTogglerDropdown">
          <ul class="navbar-nav me-auto mb-7 mb-lg-0 offset-md-7">
            <% if user_signed_in? %>
              <li><%= link_to 'マイページ', users_my_page_path(current_user),class: 'nav-link active' %></li>
              <li><!--%= link_to '商品一覧', items_path,class: 'nav-link active' %--></li>
              <li><!--%= link_to 'カート', cart_items_path,class: 'nav-link active' %--></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path,class: 'nav-link active', method: :delete %></li>
            <% else %>
              <li><!--%= link_to 'トップ', about_path,class: 'nav-link active' %--></li>
              <li><!--%= link_to '投稿一覧', admins_items_path,class: 'nav-link active' %--></li>
              <li><%= link_to '新規登録', new_user_registration_path,class: 'nav-link active' %></li>
              <li><%= link_to 'ログイン', new_user_session_path,class: 'nav-link active' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <%= yield %>
  </main>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <footer class="footer mt-auto py-3">
        <div class="container">


        </div>
      </footer>
    </nav>
  </body>
</html>

app/views/users/my_pages/edit.html.erb
<br><br><br><br>
<div class="container">
  <h2>マイページ編集</h2>
  <%= form_with model: @user, url: users_my_page(@user.id), local:true do |f| %>
    <div class="col">
      <div class='row'>
      名前(ニックネーム可)
        <%= f.text_field :name, class: 'form-control', placeholder: "釣りのすすめ", autofocus: true %>
      </div>
    <br>

      <div class='row'>
        <%= f.label :都道府県 %>
        <%= f.email_field :prefecture, class: 'form-control', placeholder: "東京都", autofocus: true %>
      </div><br>

      <div class='row'>
        <%= f.label :主な釣り場 %>
        <%= f.email_field :spot, class: 'form-control', placeholder: "堤防", autofocus: true %>
      </div><br>

      <div class='row'>
        <%= f.label :自己紹介 %>
        <%= f.email_field :introduction, class: 'form-control', placeholder: "自己紹介", autofocus: true %>
      </div><br>
    </div>
    <div class="col">
      <%= f.attachment_field :profile_image %>
    </div>

    <div class="row">
      <div class="col-md-3 offset-md-4">
        <%= f.submit "マイページ更新", class: 'btn btn-success btn-sm' %>
      </div>
    </div><br>
  <% end %>
  <div class="row">
    <%= link_to "退会する", users_my_page_unsubscribe_path, class: 'btn btn-danger btn-lg'%>
  </div>
</div>

app/views/users/my_pages/show.html.erb
<br><br><br><br>
<div class="container">
  <h2>投稿詳細</h2>
  <div class="row">
    <div class="col">
      <%= @user.name %>
      <%= @user.prefecture %>
      <%= @user.spot %>
      <%= @user.introduction %>
      <%= link_to "編集する", edit_users_my_page_path(@user.id), class: 'btn btn-success btn-lg' %>
    </div>
    <div class="col">
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "" %>
    </div>
  </div>
</div>

app/views/users/posts/index.html.erb
<br><br><br><br>
<div class="container">
  <h2>投稿一覧</h2>
  <div class="row">
    <% @posts.each do |post| %>
      <%= link_to post.user.name, users_post_path(post.id) %>
      <p><%= attachment_image_tag @post_file, :post_files_image, size: "270×200", fallback: "" %></p>
      <h6><%= link_to post.title, users_post_path(post.id) %></h6>
      <p><%= post.text %></p>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>

app/views/users/posts/new.html.erb
<br><br>
<div class="container">
  <div class="py-5 text-center">
    <h2>新規投稿</h2>
  </div>
  <%= form_with model: @post, url: users_posts_path, local:true do |f| %>
    <h5>釣り場ジャンル</h5>
    <div class="row">
      <div class="mr-3">
        <%= f.radio_button :fishing_spot_id, :海, checked: true %>
        <%= f.label :海, class: "fishing_spot_id_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :fishing_spot_id, :湖 %>
        <%= f.label :湖, class: "fishing_spot_id_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :fishing_spot_id, :川 %>
        <%= f.label :川, class: "fishing_spot_id_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :fishing_spot_id, :その他 %>
        <%= f.label :その他, class: "fishing_spot_id_label" %><br>
      </div>
    </div>
    <h5>釣り場種類</h5>
    <div class="row">
      <div class="mr-3">
        <%= f.radio_button :spot_type, :河川, checked: true %>
        <%= f.label :河川, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :湖 %>
        <%= f.label :湖, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :池 %>
        <%= f.label :池, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :港 %>
        <%= f.label :港, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :堤防 %>
        <%= f.label :堤防, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :海岸 %>
        <%= f.label :海岸, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :磯 %>
        <%= f.label :磯, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :沖 %>
        <%= f.label :沖, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :海上釣り堀 %>
        <%= f.label :海上釣り堀, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :管理釣り堀 %>
        <%= f.label :管理釣り堀, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :カセ %>
        <%= f.label :カセ, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :イカダ %>
        <%= f.label :イカダ, class: "spot_type_label" %><br>
      </div>
      <div class="mr-3">
        <%= f.radio_button :spot_type, :その他 %>
        <%= f.label :その他, class: "spot_type_label" %><br>
      </div>
    </div>
    <div class="row">
      <h5>釣り方</h5>
      <div class="mr-3">
        <%= f.text_field :fishing, placeholder: "釣り方", size: "40" %>
      </div>
    </div>
    <div class="row">
      <h5>釣り魚</h5>
      <div class="mr-3">
        <%= f.text_field :fish, placeholder: "釣り魚", size: "40" %>
      </div>
    </div>

    <!--地図機能-->

    <div class="row">
      <h5>釣果画像(ShiftまたはCtrlキーを押しながら複数選択ができます)</h5>
        <%= f.attachment_field :post_files_images, multiple: true %>
      <div class="mr-3">
      </div>
    </div>
    <div class="row">
      <h5>タイトル</h5>
      <div class="mr-3">
        <%= f.text_field :title, placeholder: "タイトル", size: "40" %>
      </div>
    </div>
    <div class="row">
      <h5>テキスト</h5>
      <div class="mr-3">
        <%= f.text_area :text, placeholder: "テキスト", size: "40×15" %>
      </div>
    </div>
    <div class="text-center">
      <%= f.submit "新規投稿", class: 'btn btn-success btn-lg' %>
    </div>
  <% end %>
</div>
<br><br>

app/views/users/posts/show.html.erb
<br><br><br><br>
<div class="container">
  <h2>投稿詳細</h2>
  <div class="row">
    <!--% link_to マイページ %-->
      <%= attachment_image_tag @user, :profile_image, :fill, 10, 10, fallback: "" %>
      <%= @user.name %>
    <!--% end %-->
    <div class="col">
      <p><%= attachment_image_tag @post_file, :post_files_image, size: "270×200", fallback: "" %>
    </div>
    <div class="col">
      <!--地図-->
    </div>
  </div>
</div>
<div class="container col">
  <div class="text-center">
    <%= @post.title %>
  </div>
  <div class="text-center">
    <%= @post.text %>
  </div>
</div>
<div class="container col">
  <div class="text-center">
    <%= @post.fishing_spot_id %>
    <%= @post.spot_type %>
    <%= @post.fishing %>
    <%= @post.fish %>
  </div>
</div>
<div class="container col">
  <div class="text-center">
    <%= link_to "編集する", edit_users_post_path(@post.id), class: 'btn btn-success btn-lg' %>
  </div>
</div>
<br><br>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>